### ISSUE TITLE
Does not compile on nightly

### ISSUE THREAD

**Issue by natemara** [ogham/rust-datetime#2]
Compiling datetime v0.1.5
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:88:117: 88:127 error: type `collections::string::String` does not implement any method in scope named `as_slice`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:88             Field::MonthName(true, a)     => a.format(w, locale.long_month_name(when.month().months_from_january()).as_slice()),
																																																												^~~~~~~~~~
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:88:117: 88:127 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:88:117: 88:127 help: candidate #1: use `core::str::Str`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:89:118: 89:128 error: type `collections::string::String` does not implement any method in scope named `as_slice`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:89             Field::MonthName(false, a)    => a.format(w, locale.short_month_name(when.month().months_from_january()).as_slice()),
																																																												 ^~~~~~~~~~
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:89:118: 89:128 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:89:118: 89:128 help: candidate #1: use `core::str::Str`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:91:114: 91:124 error: type `collections::string::String` does not implement any method in scope named `as_slice`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:91             Field::WeekdayName(true, a)   => a.format(w, locale.long_day_name(when.weekday().days_from_sunday()).as_slice()),
																																																											 ^~~~~~~~~~
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:91:114: 91:124 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:91:114: 91:124 help: candidate #1: use `core::str::Str`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:92:115: 92:125 error: type `collections::string::String` does not implement any method in scope named `as_slice`
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:92             Field::WeekdayName(false, a)  => a.format(w, locale.short_day_name(when.weekday().days_from_sunday()).as_slice()),
																																																											  ^~~~~~~~~~
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:92:115: 92:125 help: methods from traits can only be called if the trait is in scope; the following trait is implemented but not in scope, perhaps add a `use` for it:
	/home/nate/.multirust/toolchains/nightly/cargo/registry/src/github.com-1ecc6299db9ec823/datetime-0.1.5/src/format.rs:92:115: 92:125 help: candidate #1: use `core::str::Str`
	error: aborting due to 4 previous errors
	Build failed, waiting for other jobs to finish...
	Could not compile `datetime`.

**Comment by ogham** [comment]
Fixed in https://github.com/ogham/rust-datetime/commit/3a8ea0dbfcae08f70ffa7d57ca25301173912470! I forgot to `cargo publish`. Again.
